# Generated by Django 5.1.3 on 2024-11-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='name',
            field=models.CharField(default='Finu', max_length=100),
            preserve_default=False,
        ),
    ]
